/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch02;

import ch02.domain.Apple;
import ch02.enums.Color;
import ch02.formatter.AppleFancyFormatter;
import ch02.formatter.AppleFormatter;
import ch02.predicate.AppleGreenColorPredicate;
import ch02.predicate.ApplePredicate;
import ch02.predicate.Predicate;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class App {
    public static void main(String[] args) {
        List<Apple> apples = createInventory();

        System.out.println("All apples:");
        Apple apple = Apple.builder().weight(151).build();
        prettyPrintApple(apples, new AppleFancyFormatter());

        System.out.println("\nGreen apples:");
        List<Apple> greenApples = filterApples(apples, new AppleGreenColorPredicate());
        prettyPrintApple(greenApples, new AppleFancyFormatter());

        System.out.println("\nRed apples:");
        List<Apple> redApples = filter(apples, (Apple a) -> Color.RED.equals(a.getColor()));
        prettyPrintApple(redApples, new AppleFancyFormatter());

        System.out.println("\nSorted by weight:");
        apples.sort(Comparator.comparing(Apple::getWeight));
        apples.forEach((System.out::println));
    }

    public static void prettyPrintApple(List<Apple> apples, AppleFormatter formatter) {
        for (Apple apple : apples) {
            System.out.println(formatter.accept(apple));
        }
    }

    public static List<Apple> filterApples(List<Apple> inventory, ApplePredicate predicate) {
        List<Apple> apples = new ArrayList<>();
        for (Apple apple : inventory) {
            if (predicate.test(apple)) {
                apples.add(apple);
            }
        }
        return apples;
    }

    public static <T> List<T> filter(List<T> list, Predicate<T> p) {
        List<T> result = new ArrayList<>();
        for (T e : list) {
            if (p.test(e)) {
                result.add(e);
            }
        }
        return result;
    }

    public static List<Apple> createInventory() {
        List<Apple> apples = new ArrayList<>();

        apples.add(Apple.builder().color(Color.GREEN).weight(151).build());
        apples.add(Apple.builder().color(Color.RED).weight(5).build());
        apples.add(Apple.builder().color(Color.GREEN).weight(10).build());
        apples.add(Apple.builder().color(Color.RED).weight(151).build());
        apples.add(Apple.builder().color(Color.GREEN).weight(20).build());
        apples.add(Apple.builder().color(Color.RED).weight(160).build());
        apples.add(Apple.builder().color(Color.GREEN).weight(8).build());
        apples.add(Apple.builder().color(Color.RED).weight(200).build());
        apples.add(Apple.builder().color(Color.GREEN).weight(300).build());
        apples.add(Apple.builder().color(Color.RED).weight(3).build());
        return  apples;
    }
}
